version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: rating_system_db
    environment:
      POSTGRES_DB: rating_system
      POSTGRES_USER: rating_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "0.0.0.0:54331:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rating_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  rating_network:
    driver: bridge
